---
galaxy_info:
  author: Sean Mooney
  description: Setup Claude CLI and AI agents for code review
  company: Red Hat
  license: Apache-2.0
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - jammy
        - focal
    - name: Debian
      versions:
        - bullseye
        - bookworm
  galaxy_tags:
    - ai
    - codereview
    - claude
    - openstack

dependencies: []
